export const WorldAbi = [
  {
    inputs: [
      { internalType: "address", name: "_rakeRecipient", type: "address" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  { inputs: [], name: "ECDSAInvalidSignature", type: "error" },
  {
    inputs: [{ internalType: "uint256", name: "length", type: "uint256" }],
    name: "ECDSAInvalidSignatureLength",
    type: "error",
  },
  {
    inputs: [{ internalType: "bytes32", name: "s", type: "bytes32" }],
    name: "ECDSAInvalidSignatureS",
    type: "error",
  },
  {
    inputs: [{ internalType: "address", name: "owner", type: "address" }],
    name: "OwnableInvalidOwner",
    type: "error",
  },
  {
    inputs: [{ internalType: "address", name: "account", type: "address" }],
    name: "OwnableUnauthorizedAccount",
    type: "error",
  },
  { inputs: [], name: "ReentrancyGuardReentrantCall", type: "error" },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "serverId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "controller",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint96",
        name: "buyInAmount",
        type: "uint96",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "massPerEth",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint16",
        name: "rakeShareBps",
        type: "uint16",
      },
      {
        indexed: false,
        internalType: "uint16",
        name: "worldShareBps",
        type: "uint16",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "exitHoldMs",
        type: "uint32",
      },
    ],
    name: "AddedServer",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "player",
        type: "address",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "serverId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "depositId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "spawnAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "worldAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "rakeAmount",
        type: "uint256",
      },
    ],
    name: "Deposit",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "player",
        type: "address",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "serverId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "sessionId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "payout",
        type: "uint256",
      },
    ],
    name: "Exit",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "recipient",
        type: "address",
      },
    ],
    name: "RakeRecipientUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "serverId",
        type: "bytes32",
      },
    ],
    name: "RemovedServer",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "serverId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "controller",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint96",
        name: "buyInAmount",
        type: "uint96",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "massPerEth",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint16",
        name: "rakeShareBps",
        type: "uint16",
      },
      {
        indexed: false,
        internalType: "uint16",
        name: "worldShareBps",
        type: "uint16",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "exitHoldMs",
        type: "uint32",
      },
    ],
    name: "UpdatedServer",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "recipient",
        type: "address",
      },
    ],
    name: "WorldRecipientUpdated",
    type: "event",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "serverId", type: "bytes32" },
      {
        components: [
          { internalType: "address", name: "controller", type: "address" },
          { internalType: "uint96", name: "buyInAmount", type: "uint96" },
          { internalType: "uint32", name: "massPerEth", type: "uint32" },
          { internalType: "uint16", name: "rakeShareBps", type: "uint16" },
          { internalType: "uint16", name: "worldShareBps", type: "uint16" },
          { internalType: "uint32", name: "exitHoldMs", type: "uint32" },
        ],
        internalType: "struct World.ServerConfig",
        name: "config",
        type: "tuple",
      },
    ],
    name: "addServer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "serverId", type: "bytes32" },
    ],
    name: "deposit",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "depositNonce",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "serverId", type: "bytes32" },
      { internalType: "bytes32", name: "sessionId", type: "bytes32" },
      { internalType: "uint256", name: "payout", type: "uint256" },
      { internalType: "uint256", name: "deadline", type: "uint256" },
      { internalType: "bytes", name: "signature", type: "bytes" },
    ],
    name: "exitWithSignature",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "", type: "bytes32" },
      { internalType: "bytes32", name: "", type: "bytes32" },
    ],
    name: "exitedSessions",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "serverId", type: "bytes32" }],
    name: "getServer",
    outputs: [
      {
        components: [
          { internalType: "address", name: "controller", type: "address" },
          { internalType: "uint96", name: "buyInAmount", type: "uint96" },
          { internalType: "uint32", name: "massPerEth", type: "uint32" },
          { internalType: "uint16", name: "rakeShareBps", type: "uint16" },
          { internalType: "uint16", name: "worldShareBps", type: "uint16" },
          { internalType: "uint32", name: "exitHoldMs", type: "uint32" },
        ],
        internalType: "struct World.ServerConfig",
        name: "config",
        type: "tuple",
      },
      { internalType: "uint256", name: "bankroll", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "rakeRecipient",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "serverId", type: "bytes32" }],
    name: "removeServer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "recipient", type: "address" }],
    name: "setRakeRecipient",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "to", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "sweep",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "serverId", type: "bytes32" },
      {
        components: [
          { internalType: "address", name: "controller", type: "address" },
          { internalType: "uint96", name: "buyInAmount", type: "uint96" },
          { internalType: "uint32", name: "massPerEth", type: "uint32" },
          { internalType: "uint16", name: "rakeShareBps", type: "uint16" },
          { internalType: "uint16", name: "worldShareBps", type: "uint16" },
          { internalType: "uint32", name: "exitHoldMs", type: "uint32" },
        ],
        internalType: "struct World.ServerConfig",
        name: "config",
        type: "tuple",
      },
    ],
    name: "updateServer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "worldRecipient",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
] as const;

